### ISSUE TITLE
Does date math with QuarterOfYear plugin not work?

### ISSUE THREAD

**Issue by roy-miller** [elifent/dayjs#1]
I love the library, because it's the only way I can find to use Dayjs in Google Apps Script, so thanks! The only question I have is why the following code doesn't work:

`dayjs().subtract(1, 'Q');
dayjs().subtract(1, 'quarter');`

Neither of those actually subtracts 1 quarter from the initial date. Other things seem to work, like `quarter()` (returns the date's quarter), `quarter(n)` (sets the date's quarter),  and `startOf('quarter')` (returns the correct quarter start date). It looks like the modifications to `subtract` in Dayjs didn't take. Am I doing something wrong, or is the library incomplete somehow?

Thanks again.

**Comment by aneesshameed** [comment]
Thanks for the head up. The problem is described in this thread. https://github.com/iamkun/dayjs/issues/1207

I have added a fix for the same and updated a new library version. Please use version #3 🙌
