### ISSUE TITLE
Are add() and startOf() not working correctly?

### ISSUE THREAD

**Issue by roy-miller** [elifent/dayjs#2]
Either I'm doing something wrong, or there's an issue with adding months to dates. Examples:

`console.log(dayjs('2022-01-01').month()); // yields 0 (as expected for January)`
`console.log(dayjs('2022-01-01').add(1, 'month').month()); // yields 11 (but should be 1, shouldn't it?)`
`console.log(dayjs('2022-02-01').add(1, 'month').month()); // yields 0 (but should be 2)`
`console.log(dayjs('2022-03-01').add(1, 'month').month()); // yields 1 (but should be 3)`

And `startOf('quarter')` behaves strangely as well. Examples:

`console.log(dayjs('2022-01-01').startOf('quarter').toDate()); // yields December 1, 2021`

I'm stumped.

**Comment by aneesshameed** [comment]
Thank You,
I am looking into this.
Meanwhile, could you use version #1 of the library, also when subtract method doesn't work properly please use add with a negative number.

For eg:
dayjs().subtract(**1**, 'quarter'); can be also done with dayjs().add(**-1**, 'quarter');

**Comment by roy-miller** [comment]
Sure, I can use negative addition for the time being.

**Comment by roy-miller** [comment]
Something definitely changed between versions 2 and 3 (2 is the earliest I can see in GAS). `startOf('quarter')` produces the expected output in version 2, as does `add(1, 'month')`. Hope that helps you track things down.

**Comment by roy-miller** [comment]
Any thoughts or progress on this? I'm using version 2 of the library (version 1 wasn't available to me) and it's working decently, but I imagine version 3 is better and I'd like to shift to it when it's ready.

**Comment by aneesshameed** [comment]
I have deployed a new version #4. Please use it. I have tested it and it's working perfectly.
What I understood is plugin https://day.js.org/docs/en/plugin/object-support is having some core methods for addition and subtraction and these methods were getting overridden by the other libraries.

```
function foo(e) {
  const dayjs = _dayjs.load()

  console.log(dayjs('2022-01-01').month()); // 0
  console.log(dayjs('2022-01-01').add(1, 'month').month()); // 1
  console.log(dayjs('2022-02-01').add(1, 'month').month()); // 2
  console.log(dayjs('2022-03-01').add(1, 'month').month()); // 3

  console.log(dayjs('2022-01-01').startOf('quarter').format("MMM DD YYYY")); // Jan 01 2022
  console.log(dayjs('2022-01-01').subtract(1, 'Q').format("MMM DD YYYY")); // Oct 01 2022
  console.log(dayjs('2022-01-01').subtract(1, 'quarter').format("MMM DD YYYY")); // OCt 01 2022
}
```
![image](https://user-images.githubusercontent.com/12719773/193950992-d70934ff-5843-494d-bc6b-3fa48fa97f6a.png)

I appreciate your help in finding the error in the library. 🙌
